# Generated by Django 5.2.4 on 2025-07-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='configurationtest',
            name='emails_notification',
        ),
        migrations.AddField(
            model_name='configurationtest',
            name='emails_notification',
            field=models.ManyToManyField(blank=True, to='core.emailnotification'),
        ),
    ]
