# Generated by Django 5.2.4 on 2025-07-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configurationtest_last_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='redmine_slug',
            field=models.CharField(default='testwr', max_length=100),
            preserve_default=False,
        ),
    ]
