# Generated by Django 5.2.4 on 2025-07-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_projet_id_redmine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationtest',
            name='axes',
        ),
        migrations.RemoveField(
            model_name='configurationtest',
            name='sous_axes',
        ),
        migrations.AlterField(
            model_name='projet',
            name='id_redmine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
