# Generated by Django 5.2.4 on 2025-08-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_executiontest_statut_executionresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executionresult',
            options={'verbose_name': "Résultat d'exécution de script", 'verbose_name_plural': 'Résultats des scripts'},
        ),
    ]
