# Generated by Django 5.2.4 on 2025-08-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_executionresult_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionresult',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('done', 'Concluant'), ('error', 'Non concluant'), ('non_executed', 'Non exécuté')], max_length=20),
        ),
        migrations.AlterField(
            model_name='executiontest',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('done', 'Concluant'), ('error', 'Non concluant'), ('non_executed', 'Non exécuté')], default='pending', max_length=20),
        ),
    ]
