# Generated by Django 5.2.4 on 2025-08-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_configurationtest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationtest',
            name='date_activation',
            field=models.DateTimeField(blank=True, help_text='Date et heure de lancement de la configuration', null=True),
        ),
        migrations.AlterField(
            model_name='configurationtest',
            name='date_desactivation',
            field=models.DateTimeField(blank=True, help_text='Date et heure de désactivation de la configuration', null=True),
        ),
    ]
