# Generated by Django 5.2.4 on 2025-09-15 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0023_script_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupePersonnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type_groupe', models.CharField(choices=[('predéfini', 'Prédéfini'), ('personnalisé', 'Personnalisé')], default='personnalisé', max_length=20)),
                ('role_predefini', models.CharField(blank=True, choices=[('administrateur', 'Administrateur'), ('qa', 'Quality Assurance'), ('developpeur', 'Développeur'), ('manager', 'Manager'), ('chef_projet', 'Chef de Projet')], max_length=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('est_protege', models.BooleanField(default=False)),
                ('groupe_django', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_personnalise', to='auth.group')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'verbose_name': 'Groupe personnalisé',
                'verbose_name_plural': 'Groupes personnalisés',
            },
        ),
    ]
