# Generated by Django 5.2.4 on 2025-09-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_groupepersonnalise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_dashboard', 'Can view dashboard')], 'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboard'},
        ),
    ]
