# Generated by Django 5.2.4 on 2025-09-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_configurationtest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationtest',
            options={'ordering': ['nom'], 'verbose_name': 'Configuration Test', 'verbose_name_plural': 'Configurations Test'},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'default_permissions': (), 'managed': False, 'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboard'},
        ),
    ]
