# Generated by Django 5.2.4 on 2025-09-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_redmineproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedmineProject',
        ),
    ]
