# Generated by Django 5.2.4 on 2025-09-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_configuration_last_sync_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedmineProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(unique=True, verbose_name='ID Redmine')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('identifier', models.CharField(max_length=255, verbose_name='Identifiant')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('homepage', models.URLField(blank=True, verbose_name='Homepage')),
                ('parent_name', models.CharField(blank=True, max_length=255, verbose_name='Parent')),
                ('status', models.IntegerField(verbose_name='Statut')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('created_on', models.DateTimeField(blank=True, null=True, verbose_name='Créé le')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Mis à jour le')),
                ('manager', models.CharField(blank=True, max_length=255, verbose_name='Manager')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Dernière synchronisation')),
            ],
            options={
                'verbose_name': 'Projet Redmine',
                'verbose_name_plural': 'Projets Redmine',
            },
        ),
    ]
