# Generated by Django 5.2.4 on 2025-09-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_redmineproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière synchronisation'),
        ),
    ]
