# Generated by Django 5.2.4 on 2025-09-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_configuration_last_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
