# Generated by Django 5.2.4 on 2025-09-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_configuration_last_sync_alter_projet_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='redmine_slug',
        ),
        migrations.AlterField(
            model_name='projet',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
