# Generated by Django 5.2.4 on 2025-09-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_projet_redmine_slug_alter_projet_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'default_permissions': (), 'managed': False, 'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboards'},
        ),
    ]
