# Generated by Django 5.2.4 on 2025-09-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_dashboard_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'default_permissions': (), 'managed': False, 'verbose_name': 'Dashboard1', 'verbose_name_plural': 'Dashboards'},
        ),
    ]
