# Generated by Django 5.1.4 on 2025-09-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_secteuractivite_alter_dashboard_options_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='url',
            field=models.URLField(blank=True, help_text='URL du site web de la société', null=True),
        ),
    ]
