# Generated by Django 5.1.4 on 2025-09-23 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_societe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='employes',
            field=models.ManyToManyField(blank=True, related_name='societes_employes', to=settings.AUTH_USER_MODEL),
        ),
    ]
