# Generated by Django 5.1.4 on 2025-10-02 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_customuser_societe_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='societe',
            name='projet',
        ),
        migrations.AddField(
            model_name='societe',
            name='projets',
            field=models.ManyToManyField(blank=True, related_name='societes', to='core.projet'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='societe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.societe', verbose_name='Société'),
            preserve_default=False,
        ),
    ]
