# Generated by Django 5.1.4 on 2025-10-02 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_customuser_options_remove_societe_projet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='charge_de_compte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_charge_de_compte', to=settings.AUTH_USER_MODEL),
        ),
    ]
