# Generated by Django 5.1.4 on 2025-10-03 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_projet_charge_de_compte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnotification',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Email de notification', 'verbose_name_plural': 'Emails de notification'},
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emails_crees', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='est_actif',
            field=models.BooleanField(default=True, help_text='Indique si cet email reçoit des notifications'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='societe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emails_notification', to='core.societe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='societe',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='societe',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='configurationtest',
            name='emails_notification',
            field=models.ManyToManyField(blank=True, limit_choices_to={'est_actif': True}, to='core.emailnotification'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
