# Generated by Django 5.1.4 on 2025-10-03 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_emailnotification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnotification',
            options={},
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails_notification', to='core.societe'),
        ),
    ]
