# Generated by Django 5.1.4 on 2025-10-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_emailnotification_options_and_more'),
        ('core', '0047_auto_20251003_0855'),
    ]

    operations = [
    ]
