# Generated by Django 5.1.4 on 2025-10-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_merge_20251003_0901'),
        ('core', '0049_add_missing_fields_to_emailnotification'),
    ]

    operations = [
    ]
