# Generated by Django 5.1.4 on 2025-10-03 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_merge_20251003_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
