# Generated by Django 5.1.4 on 2025-10-03 10:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_emailnotification_date_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': 'Configuration', 'verbose_name_plural': 'Configurations'},
        ),
        migrations.AlterModelOptions(
            name='emailnotification',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Email de notification', 'verbose_name_plural': 'Emails de notification'},
        ),
        migrations.AddField(
            model_name='configuration',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='societe',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='core.societe', verbose_name='Société'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redmineproject',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redmine_projects', to='core.societe'),
        ),
    ]
