# Generated by Django 5.1.4 on 2025-10-03 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_configuration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='societe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='core.societe', verbose_name='Société'),
        ),
    ]
