# Generated by Django 5.1.4 on 2025-10-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_configuration_societe'),
        ('core', '0054_populate_configuration_data'),
    ]

    operations = [
    ]
