# Generated by Django 5.1.4 on 2025-10-03 12:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_merge_20251003_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationtest',
            options={'ordering': ['nom'], 'permissions': [('view_societe_configurationtest', 'Peut voir les configurations test de sa société'), ('change_societe_configurationtest', 'Peut modifier les configurations test de sa société'), ('delete_societe_configurationtest', 'Peut supprimer les configurations test de sa société')], 'verbose_name': 'Configuration Test', 'verbose_name_plural': 'Configurations Test'},
        ),
        migrations.AddField(
            model_name='configurationtest',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configurationtest',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configurationtest',
            name='societe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='configurations_test', to='core.societe', verbose_name='Société'),
            preserve_default=False,
        ),
    ]
