# Generated by Django 5.1.4 on 2025-10-09 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_configurationtest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemeScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_probleme', models.CharField(choices=[('timeout', 'Timeout'), ('configuration_invalide', 'Configuration invalide'), ('element_non_trouve', 'Élément non trouvé'), ('erreur_reseau', 'Erreur réseau'), ('resource_non_disponible', 'Resource non disponible'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField()),
                ('frequence_probleme', models.CharField(help_text='Description de la fréquence du problème', max_length=100)),
                ('derniere_execution', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('critique', 'Critique'), ('en_attente_resolution', 'En attente de résolution'), ('surveille', 'Surveillé'), ('resolu', 'Résolu')], default='en_attente_resolution', max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemes', to='core.script')),
            ],
            options={
                'verbose_name': 'Problème de script',
                'verbose_name_plural': 'Problèmes de scripts',
                'ordering': ['-date_creation'],
            },
        ),
    ]
