# Generated by Django 5.1.4 on 2025-10-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_problemescript'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom'),
        ),
    ]
