# Generated by Django 5.1.4 on 2025-10-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_emailnotification_nom_emailnotification_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societe',
            name='num_siret',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='url',
        ),
    ]
