# Generated by Django 5.1.4 on 2025-10-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_societe_num_siret_remove_societe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupepersonnalise',
            name='role_predefini',
            field=models.CharField(blank=True, choices=[('super-admin', 'Super-admin'), ('admin-societe', 'admin-societe'), ('manager', 'Manager'), ('chef_projet', 'Chef de projet'), ('qa', 'QA')], max_length=20, null=True),
        ),
    ]
