# Generated by Django 5.2.4 on 2025-07-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationtest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
