# Generated by Django 5.2.4 on 2025-07-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configurationtest_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationtest',
            name='last_execution',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
