# Generated by Django 5.2.4 on 2025-07-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_configurationtest_axes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiontest',
            name='ticket_redmine_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
