# Generated by Django 5.2.4 on 2025-07-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='id_redmine_charge_de_compte',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
