# Generated by Django 5.2.4 on 2025-07-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_projet_id_redmine_charge_de_compte'),
    ]

    operations = [
        migrations.CreateModel(
            name='VueGlobale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Vue Globale',
                'verbose_name_plural': 'Vue Globale',
                'managed': False,
            },
        ),
    ]
