# Generated by Django 5.2.4 on 2025-07-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_vueglobale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redmine_url', models.URLField(blank=True, null=True, verbose_name='URL Redmine')),
                ('redmine_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Clé API Redmine')),
                ('email_host_user', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Host User')),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot de passe Email')),
            ],
            options={
                'verbose_name': 'Paramètre global',
                'verbose_name_plural': 'Paramètres globaux',
            },
        ),
    ]
