# Generated by Django 5.2.4 on 2025-08-04 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_script_priorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiontest',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('done', 'Concluant'), ('error', 'Non concluant')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('done', 'Concluant'), ('error', 'Non concluant')], max_length=20)),
                ('log_fichier', models.FileField(blank=True, null=True, upload_to='logs/')),
                ('commentaire', models.TextField(blank=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='core.executiontest')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.script')),
            ],
        ),
    ]
