# Generated by Django 5.2.4 on 2025-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_executionresult_statut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationtest',
            options={'ordering': ['nom'], 'verbose_name': 'Configuration Test', 'verbose_name_plural': 'Configurations Test'},
        ),
        migrations.AlterField(
            model_name='configurationtest',
            name='date_activation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configurationtest',
            name='date_desactivation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
