# Generated by Django 5.2.4 on 2025-09-15 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_configurationtest_date_activation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='core.projet'),
        ),
    ]
