# Generated by Django 5.2.4 on 2025-09-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_dashboard_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationtest',
            options={'ordering': ['nom'], 'permissions': [('can_view_configurationtest', 'Can view configuration test')], 'verbose_name': 'Configuration Test', 'verbose_name_plural': 'Configurations Test'},
        ),
    ]
