# Generated by Django 5.2.4 on 2025-09-16 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_configurationtest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedmineProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(unique=True, verbose_name='ID Redmine')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('manager', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('last_sync', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière synchronisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Projet Redmine',
                'verbose_name_plural': 'Projets Redmine',
            },
        ),
    ]
