# Generated by Django 5.2.4 on 2025-09-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_delete_redmineproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière synchronisation'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='redmine_projects',
            field=models.JSONField(blank=True, default=list, verbose_name='Projets Redmine'),
        ),
    ]
