# Generated by Django 5.2.4 on 2025-09-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_configuration_last_sync_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='redmine_projects',
        ),
    ]
