# Generated by Django 5.2.4 on 2025-09-17 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_projet_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='last_sync',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Dernière synchronisation'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='logo',
            field=models.ImageField(upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='redmineproject',
            name='last_sync',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Dernière synchronisation'),
        ),
    ]
